USE UnitedOutdoors;

ALTER TABLE Product
ADD CONSTRAINT Product_Date_SellStartDateFK
FOREIGN KEY (PRODUCT_DATE_SellStartDateFK)
REFERENCES Date(DATE_ID)
GO

ALTER TABLE Product
ADD CONSTRAINT Product_Date_SellEndDateFK
FOREIGN KEY (PRODUCT_DATE_SellEndDateFK)
REFERENCES Date(DATE_ID)
GO

ALTER TABLE Product
ADD CONSTRAINT Product_Date_DiscountedDateFK
FOREIGN KEY (PRODUCT_DATE_DiscountedDateFK)
REFERENCES Date(DATE_ID)
GO

ALTER TABLE Product
ADD CONSTRAINT FK_Product_Supplier
FOREIGN KEY (PRODUCT_PRODUCT_SupplierID)
REFERENCES Supplier(SUPPLIER_sk)
GO

ALTER TABLE Product
ADD CONSTRAINT FK_Product_UnitMeasure_Size
FOREIGN KEY (PRODUCT_UNITMEASURE_SIZE_ID)
REFERENCES UnitMeasure(UNITMEASURE_sk)
GO

ALTER TABLE Product
ADD CONSTRAINT FK_Product_UnitMeasure_Weight
FOREIGN KEY (PRODUCT_UNITMEASURE_WEIGHT_ID)
REFERENCES UnitMeasure(UNITMEASURE_sk)
GO

ALTER TABLE BillOfMaterial
ADD CONSTRAINT FK_BillOfMaterial_UnitMeasure
FOREIGN KEY (BILLOFMATERIAL_UNITMEASURE_ID)
REFERENCES UnitMeasure(UNITMEASURE_sk)
GO

ALTER TABLE Document
ADD CONSTRAINT FK_Document_Product
FOREIGN KEY (DOCUMENT_PRODUCTDOCUMENT_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE WorkOrder
ADD CONSTRAINT FK_WorkOrder_Product
FOREIGN KEY (WORKORDER_WORKORDER_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE WorkOrder
ADD CONSTRAINT FK_WorkOrder_Location
FOREIGN KEY (WORKORDER_WORKORDERINGROUTING_LocationID)
REFERENCES Location(LOCATION_sk)
GO

ALTER Table Department
ADD CONSTRAINT FK_Department_Employee
FOREIGN KEY (DEPARTMENT_DEPARTMENT_DeptHeadID)
REFERENCES Employee(EMPLOYEE_sk)
GO

/*
ALTER TABLE Employee
ADD CONSTRAINT FK_Employee_BusinessEntity
FOREIGN KEY (EMPLOYEE_EMPLOYEE_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO*/

ALTER TABLE Employee
ADD CONSTRAINT FK_Employee_Department
FOREIGN KEY (EMPLOYEE_EMPLOYEE_DeptID)
REFERENCES Department(DEPARTMENT_sk)
GO

ALTER TABLE Employee
ADD CONSTRAINT FK_Employee_Manager
FOREIGN KEY (EMPLOYEE_EMPLOYEE_ManagerID)
REFERENCES Employee(EMPLOYEE_sk)
GO

ALTER TABLE BusinessEntity
ADD CONSTRAINT FK_BusinessEntity_Person
FOREIGN KEY (BUSINESSENTITY_BUSINESSENTITYCONTACT_PersonID)
REFERENCES Person(PERSON_sk)
GO

ALTER TABLE People
ADD CONSTRAINT FK_People_BusinessEntity
FOREIGN KEY (PERSON_PERSON_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO

ALTER TABLE BusinessEntityAddress
ADD CONSTRAINT FK_BusinessEntityAddress_BusinessEntity
FOREIGN KEY (BUSINESSENTITYADDRESS_BUSINESSENTITYADDRESS_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO

ALTER TABLE BusinessEntityAddress
ADD CONSTRAINT FK_BusinessEntityAddress_StateProvince
FOREIGN KEY (BUSINESSENTITYADDRESS_ADDRESS_StateProvinceID)
REFERENCES StateProvince(STATEPROVINCE_sk)
GO

ALTER TABLE Inventory
ADD CONSTRAINT FK_ProductInventory_Product
FOREIGN KEY (INVENTORY_PRODUCT_ID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE Inventory
ADD CONSTRAINT FK_Inventory_Location
FOREIGN KEY (INVENTORY_LOCATION_ID)
REFERENCES Location(LOCATION_sk)
GO

ALTER TABLE JobCandidate
ADD CONSTRAINT FK_JobCandidate_BusinessEntity
FOREIGN KEY (JOBCANDIDATE_JOBCANDIDATE_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO

ALTER TABLE EmployeeDepartmentHistory
ADD CONSTRAINT FK_EmployeeDepartmentHistory_BusinessEntity
FOREIGN KEY (EMPLOYEEDEPARTMENTHISTORY_EMPLOYEEDEPARTMENTHISTORY_ShiftID)
REFERENCES Shift(SHIFT_sk)
GO

ALTER TABLE EmployeePayHistory
ADD CONSTRAINT FK_EmployeePayHistory_BusinessEntity
FOREIGN KEY (EMPLOYEEPAYHISTORY_EMPLOYEEPAYHISTORY_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO

ALTER TABLE SalesPerson
ADD CONSTRAINT FK_SalesPerson_BusinessEntity
FOREIGN KEY (SALESPERSON_SALESPERSON_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO

ALTER TABLE SalesPerson
ADD CONSTRAINT FK_SalesPerson_Territory
FOREIGN KEY (SALESPERSON_SALESPERSON_TerritoryID)
REFERENCES Territory(TERRITORY_sk)
GO

ALTER TABLE ProductVendor
ADD CONSTRAINT FK_ProductVendor_Product
FOREIGN KEY (PRODUCTVENDOR_PRODUCTVENDOR_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE ProductVendor
ADD CONSTRAINT FK_ProductVendor_BusinessEntity
FOREIGN KEY (PRODUCTVENDOR_PRODUCTVENDOR_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO

ALTER TABLE ProductVendor
ADD CONSTRAINT FK_ProductVendor_UnitMeasureID
FOREIGN KEY (PRODUCTVENDOR_PRODUCTVENDOR_UnitMeasureCode)
REFERENCES UnitMeasure(UNITMEASURE_sk)
GO

ALTER TABLE SalesTerritoryHistory
ADD CONSTRAINT FK_SalesTerritoryHistory_BusinessEntity
FOREIGN KEY (SALESTERRITORYHISTORY_SALESTERRITORYHISTORY_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO

ALTER TABLE SalesTerritoryHistory
ADD CONSTRAINT FK_SalesTerritoryHistory_Territory
FOREIGN KEY (SALESTERRITORYHISTORY_SALESTERRITORYHISTORY_TerritoryID)
REFERENCES Territory(TERRITORY_sk)
GO

ALTER TABLE ProductListPriceHistory
ADD CONSTRAINT FK_ProductListPriceHistory_Product
FOREIGN KEY (PRODUCTLISTPRICEHISTORY_PRODUCTLISTPRICEHISTORY_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE ProductCostHistory
ADD CONSTRAINT FK_ProductCostHistory_Product
FOREIGN KEY (PRODUCTCOSTHISTORY_PRODUCTCOSTHISTORY_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE ShoppingCartItem
ADD CONSTRAINT FK_ShoppingCartItem_Product
FOREIGN KEY (SHOPPINGCARTITEM_SHOPPINGCARTITEM_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE SalesPersonQuotaHistory
ADD CONSTRAINT FK_SalesPersonQuotaHistory_BusinessEntity
FOREIGN KEY (SALESPERSONQUOTAHISTORY_SALESPERSONQUOTAHISTORY_BusinessEntityID)
REFERENCES BusinessEntity(BUSINESSENTITY_sk)
GO

ALTER TABLE SpecialOffer
ADD CONSTRAINT FK_SpecialOffer_Product
FOREIGN KEY (SPECIALOFFER_SPECIALOFFERPRODUCT_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE Customer
ADD CONSTRAINT FK_Customer_Person
FOREIGN KEY (CUSTOMER_CUSTOMER_PersonID)
REFERENCES Person(PERSON_sk)
GO

ALTER TABLE Customer
ADD CONSTRAINT FK_Customer_Territory
FOREIGN KEY (CUSTOMER_CUSTOMER_TerritoryID)
REFERENCES Territory(TERRITORY_sk)
GO

ALTER TABLE Customer
ADD CONSTRAINT FK_Customer_SalesPerson
FOREIGN KEY (CUSTOMER_STORE_SalesPersonID)
REFERENCES SalesPerson(SALESPERSON_sk)
GO

ALTER TABLE Customer
ADD CONSTRAINT FK_Customer_CountryRegion
FOREIGN KEY (CUSTOMER_SALESTERRITORY_CountryRegionCode)
REFERENCES Territory(TERRITORY_sk)
GO

ALTER TABLE CustomerCustomerDemo
ADD CONSTRAINT FK_CustomerCustomerDemo_CustomerDemographic
FOREIGN KEY (CUSTOMERCUSTOMERDEMO_CUSTOMERCUSTOMERDEMO_CustomerTypeID)
REFERENCES CustomerDemographic(CUSTOMERDEMOGRAPHIC_sk)
GO

ALTER TABLE TransactionHistory
ADD CONSTRAINT FK_TransactionHistory_Product
FOREIGN KEY (TRANSACTIONHISTORY_TRANSACTIONHISTORY_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE Currency
ADD CONSTRAINT FK_Currency_CountryRegion
FOREIGN KEY (CURRENCY_COUNTRYREGIONCURRENCY_CountryRegionCode)
REFERENCES CountryRegionTerritory(TERRITORY_sk)
GO

ALTER TABLE Currency
ADD CONSTRAINT FK_Currency_CurrencyFrom
FOREIGN KEY (CURRENCY_CURRENCYRATE_FromCurrencyCode)
REFERENCES Currency(CURRENCY_sk)
GO

ALTER TABLE Currency
ADD CONSTRAINT FK_Currency_CurrencyTo
FOREIGN KEY (CURRENCY_CURRENCYRATE_ToCurrencyCode)
REFERENCES Currency(CURRENCY_sk)
GO

ALTER TABLE SalesOrderHeader
ADD CONSTRAINT FK_SalesOrderHeader_Product
FOREIGN KEY (SALESORDERHEADER_SALESORDERDETAIL_ProductID)
REFERENCES Product(PRODUCT_sk)
GO

ALTER TABLE SalesOrderHeader
ADD CONSTRAINT FK_SalesOrderHeader_Customer
FOREIGN KEY (SALESORDERHEADER_SALESORDERHEADER_CustomerID)
REFERENCES Customer(CUSTOMER_sk)
GO

ALTER TABLE SalesOrderHeader
ADD CONSTRAINT FK_SalesOrderHeader_SpecialOffer
FOREIGN KEY (SALESORDERHEADER_SALESORDERDETAIL_SpecialOfferID)
REFERENCES SpecialOffer(SPECIALOFFER_sk)
GO

ALTER TABLE SalesOrderHeader
ADD CONSTRAINT FK_SalesOrderHeader_CreditCard
FOREIGN KEY (SALESORDERHEADER_SALESORDERHEADER_CreditCardID)
REFERENCES CreditCard(CREDITCARD_sk);
GO

/*
ALTER TABLE SalesOrderHeader
ADD CONSTRAINT FK_SalesOrderHeader_CurrencyRate
FOREIGN KEY (SALESORDERHEADER_SALESORDERHEADER_CurrencyRateID)
REFERENCES Currency(CURRENCYRATE_sk);
GO*/

ALTER TABLE PurchaseOrderHeader
ADD CONSTRAINT FK_PurchaseOrderHeader_Employee
FOREIGN KEY (PURCHASEORDERHEADER_PURCHASEORDERHEADER_EmployeeID)
REFERENCES Employee(EMPLOYEE_sk);
GO

ALTER TABLE PurchaseOrderHeader
ADD CONSTRAINT FK_PurchaseOrderHeader_Product
FOREIGN KEY (PURCHASEORDERHEADER_PURCHASEORDERDETAIL_ProductID)
REFERENCES Product(PRODUCT_sk);
GO

ALTER TABLE TransactionHistoryArchive
ADD CONSTRAINT FK_TransactionHistoryArchive_Product
FOREIGN KEY (TRANSACTIONHISTORYARCHIVE_TRANSACTIONHISTORYARCHIVE_ProductID)
REFERENCES Product(PRODUCT_sk);
GO

ALTER TABLE ProductReview
ADD CONSTRAINT FK_ProductReview_Product
FOREIGN KEY (PRODUCTREVIEW_PRODUCTREVIEW_ProductID)
REFERENCES Product(PRODUCT_sk);
GO
